language: ruby
rvm: 2.2
sudo: false
cache:
  directories:
    - vendor/bundle
    - $HOME/.npm
before_install: |
  npm install -g gitbook-cli
  bundle install --deployment --jobs=3 --retry=3
script: test $TRAVIS_PULL_REQUEST != "false" || test $TRAVIS_BRANCH != "gh-pages" || ./travis-build.sh
env:
  global:
    secure: HL5YGlpkucqkVodK+LEQo7jGx/vTRxAn08rmbFPAxuS57PC5C5b9WNhX4A46MIiFkAB9H0YDCd9wdPXEEhcAhyNImnitFhATYg3SWpJenw0V+dPH7E3qBk5YmOBHVPTDuepG7iDLwIgdFmcq0PT53PI6+EEckN5Z5YV7d/D0xMvu3xP0Y9vEM7kbIwl369Xa5aox+SnMA246K66c7cxLOav6KYeU0FhLff49k00mIbtt6bpAx4q/LOvuWXKy4xThm96C+1aCPm9NoozCmxpz7RVIra2v4b69Eqh42LXgd4rcC+jp/OYuFLQr0W7Q1u+tWUj+jd7jzA8eyCKPMY/YKB/IUZ703aFN9vcVyesCab2V+fm2s+wBrQjBZTngdsGHJSJdZFjtu07AgMaX3jPwhO7jWXJ7GYIV9flfcqgwBfgxa5EFezyVEazEhMWCNB3kjvkJTt2k1GXp3BbuIBiXZyuxDP/SJ93t/aS7EyneOYjj3piYXpXEBFM7zoZNODKi96siVfDk79Od8PhPqfSp7owH+aklBOLesc7lRDZzYQmAdBK3O29HUdnvdpXqSjkTQwF0fqYl5A/fw7aDJ0B1sgvJpQbkXdZVOPaSB5mDyE68hFxuOfg/M2KqGHq1g1I5Z8hg34QpVKHmcH+d3Y2bOtzQh9p5//tS4Y/EEL7ZeQM=
branches:
  only:
    - master
    - gh-pages

