language: ruby
rvm: 2.2
sudo: false
cache:
  directories:
    - vendor/bundle
    - $HOME/.npm
before_install: |
  npm install -g gitbook-cli
  bundle install --deployment --jobs=3 --retry=3
script: test $TRAVIS_PULL_REQUEST != "false" || test $TRAVIS_BRANCH != "gh-pages" || ./travis-build.sh
env:
  global:
    secure: 0+qED5v/4/l8wkmmAVp8jj3qlE6MpZEoj5+Ym08M16imGJ5L9EpMQUuywH19j560uEnxq6eX16evNBAS5fhwqG1one79iLy7ZYk1W9K3kmRa3fI5r8yGY6fC2b2VJsu5GCdxs2LJRxgSYX10gNAXFEIxumausgtQw+8zqNIcpLy0T4EDjb5tpIodvjV4uZ0M4uVZe4wSNKg1vRrU+vH29t0FaWYppKpAvmUqSEmVcwztGgo0qF5GvgHSPsIizAKznN86bSaFviVo8yUiMDR61kNuVNfrTJkJUaMfPyPq2KdSO3myZJBsZ1TE/4pCSplkbmAUYP479rcmfqVTiXhMCcRX/Dub4nuWYKHAt4hcui6sypfEWCjhNBBsS5svQ8dkojoBtHCC8oYfOXbxa20F5oejZCYyxjcRkP8R85hB/AkWaQugMyLD9eUd4xtG72h7pc1N181+J6kjdS8B+i0wozx3UqbwVU8B3SCCozJEdp3a38ZQeWHHPbGn+xZA+SxjeskwX5Yo+D08pdm3U9hDfcyGaAtVxxCRO9kqywKQZvXC3btGtsDcOCgUQb27rYIHRRH62xYTWMAgadefypUwvGIlxbN0NZu3gnDxn3tsgoS6WAsWVn996pWB78U6ehfrgaVPVGS7MSBKlDcBHSPQq2ilZWHVZK4N51y7+DLvPIo=
branches:
  only:
    - master
    - gh-pages
