language: ruby
rvm: 2.2
sudo: false
cache:
  directories:
    - vendor/bundle
    - $HOME/.npm
before_install: |
  npm install -g gitbook-cli
  bundle install --deployment --jobs=3 --retry=3
script: test $TRAVIS_PULL_REQUEST != "false" || test $TRAVIS_BRANCH != "gh-pages" || ./travis-build.sh
env:
  global:
    secure: A2G7kRX6MCrsyGOqfJ0QZRNjLwE7RO3GHF3cj5Gmielkzpr6WxG8MMXpY6tFvX6Vu9gcW42XsDlGDPKWjXkumSzNHvmcqcnOGiiDTeB0QqBrUZhbEF3IZB0Nvkdfwn23EqrD+j16kX0Pflh0lNTRC3x3/Bs5laORBxUy+1a4FXiYz5Fnhpq9siOvxHpUYnx6AM/zH09wiDcmnDckJKHLsf2tQb5hbl15+uMoFxQ91skIXG59R9LVunBaZ0nI8GbkkHzKO/EQPNQrxrNc8KWso+ske8yawL1Xgz0E3d+A8zSD4Ehcczjrm6XX27+TEOsQDAMT9rLCB4ddlt8xAS/OFFvdw1uJmYAGznFG7hBLq6OyvexcX/YjqJAdHnnd7b2VZnAk5ytmzJFnYQaR9opSBJDNAT4sz7/aCTtzbqaV2an5+GAAuVmj/xVIYUjih9pHDgQXr66RyBWLuqrrtrUO01gKuywmK5UvkIX7ymTxjd2nAWxDKF+mfB0vPZq+BUCG3jqACFIEzO0mlZzYJJQKf6amP4lMtgksgRr2SewkHb9OK3pTM5GRNqrOnf+GDJvX1w7lZLCuYJzJO4Ctho0eTf5a3UPshH9YEez6m07QLqdwVGjSjfr/mwE4Tcv6Mxd/+l0SDhE+6/SlXQelr4uXTsxZpDrO2dMCWTJrrSJ7a6c=
branches:
  only:
    - master
    - gh-pages
